# Copyright 2018, IBM.
#
# This source code is licensed under the Apache License, Version 2.0 found in
# the LICENSE.txt file in the root directory of this source tree.

notifications:
    on_success: change
    on_failure: always

cache: pip
os: linux
dist: trusty

language: python
python:
  - "3.6"

# Install Dependencies
# The env. variable MASTER_BRANCH_DEPENDENCIES forces dependencies used from master
env:
  - MASTER_BRANCH_DEPENDENCIES=true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenblas-dev
      - g++-7    
      
before_install:
  # download Qiskit Terra master and unzip it only if forced from master or not stable branch, otherwise use the pypi version
  - |
    if [ ${MASTER_BRANCH_DEPENDENCIES} = "true" ] || [ ${TRAVIS_BRANCH} != "stable" ]; then
      wget https://codeload.github.com/Qiskit/qiskit-terra/zip/master -O /tmp/qiskit-terra.zip
      unzip /tmp/qiskit-terra.zip -d /tmp/
      # Install Qiskit Terra requirements.
      pip install -U -r /tmp/qiskit-terra-master/requirements.txt
      pip install -U -r /tmp/qiskit-terra-master/requirements-dev.txt
      # Install local Qiskit Terra
      pip install -e /tmp/qiskit-terra-master
      wget https://codeload.github.com/Qiskit/qiskit-ibmq-provider/zip/master -O /tmp/qiskit-ibmq-provider.zip
      unzip /tmp/qiskit-ibmq-provider.zip -d /tmp/
      # Install Qiskit IBMQ Provider requirements.
      pip install -U -r /tmp/qiskit-ibmq-provider-master/requirements.txt
      pip install -U -r /tmp/qiskit-ibmq-provider-master/requirements-dev.txt
      # Install local Qiskit IBMQ Provider
      pip install -e /tmp/qiskit-ibmq-provider-master
    fi

# Test 
install:
    # install Aqua and dev requirements
    - pip install -e $TRAVIS_BUILD_DIR
    - pip install -U -r requirements-dev.txt
script:
    - python -m unittest discover -v test